### ISSUE TITLE
Cystemz come home

### ISSUE THREAD

**Issue by not-cedo** [Cystemzz/Hooky#1]
come home to me baby

**Comment by Cystemzz** [comment]
lol

**Comment by LzIP251** [comment]
suck it nigeria man

**Comment by Cystemzz** [comment]
> suck it nigeria man

And who are you?

**Comment by ghost** [comment]
> come home to me baby
![](https://media.discordapp.net/attachments/965367661875830814/997591340563042374/togif.gif)

**Comment by Cystemzz** [comment]
Hi Mark Channon, I'm sorry to inform you, but it appears this issue has been marked resolved and your reply was off topic. If you wish to open a new issue in order to get your problem resolved, you may do so.

Wishing you the best from the not the uk, Cystemzz

**Comment by ghost** [comment]
> Hi Mark Channon, I'm sorry to inform you, but it appears this issue has been marked resolved and your reply was off topic. If you wish to open a new issue in order to get your problem resolved, you may do so.
> 
> Wishing you the best from the not the uk, Cystemzz

So you don't love me? Shame.
